version: '3.7'

services:
 binternet:
  build:
      context: .
      dockerfile: Dockerfile
  container_name: binternet
  hostname: binternet
  restart: always
  security_opt:
     - no-new-privileges:true
  ports:
     - '127.0.0.1:8009:8009'
